kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: petclinic-dev
  namespace: argocd
spec:
  destination:
    namespace: petclinic-dev
    server: https://kubernetes.default.svc
  project: petclinic
  source:
    path: overlays/dev
    repoURL: https://github.com/pittar-blogs/pragmatic-gitops-01-kustomize.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
