kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: petclinic-prod
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: petclinic
  source:
    path: overlays/prod
    repoURL: https://github.com/pittar-blogs/pragmatic-gitops-01-kustomize.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true